version: '2'
services:
    jhifuse-app:
        image: jhifuse
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhifuse-postgresql:5432/jhifuse
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhifuse-postgresql:
        extends:
            file: postgresql.yml
            service: jhifuse-postgresql
